version: 2

models:
  - name: dim_customer
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique
              
  - name: dim_employee
    columns:
      - name: employee_id
        tests:
          - not_null
          - unique
  - name: stg_products
    columns:
      - name: id
        tests:
          - not_null
          - unique            